version: "3.8"

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "443:443"
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_ADMIN_USER=${DB_ADMIN_USER}
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
      - DB_NORMAL_USER=${DB_NORMAL_USER}
      - DB_NORMAL_USER_PASSWORD=${DB_NORMAL_USER_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: flask-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local
